##
# Defines site data and metadata
#
# Author: Matt Turner <matt@mat.phd>
# Date: 15 June 2026
#


website:

  title: "Cumulus.Community"

  navbar:
    # background: "#55ddff"
    background: "#9080A0"
    foreground: "#FFF"

  favicon: images/cumulus-community-lettermark.png

  search: false

  open-graph:
    image: images/cumulus-community-lettermark.jpg
  twitter-card:
    image: images/cumulus-community-lettermark.jpg
    card-style: summary_large_image

format:

  html:

    search: false
    theme:
      - cosmo
      - brand
      - styles.scss

    # css: styles.scss
    toc: false


project:
  type: website
